This repository contains a simple program to enumerate small semigroup actions and faithful Wilke algebras (equivalently, finite ω-semigroups). There are also output files provided. It requires an enumeration of small semigroups as input, see Andreas Distler's [[https://research-repository.st-andrews.ac.uk/handle/10023/945][PhD thesis]]. This arose to compute with thin tree algebras and we also provide some tools for those.
* Algorithm
We use multiplication tables of all semigroups up to size n as input. For each such semigroup G we compute a minimal generating subset {x(1), ..., x(n)}. Set G(i)=<x(i), ..., x(i)>. We now recursively compute all actions of G on sets of size up to m. Such an action is given by a pair of an action of G(n-1), which have been enumerated by recursion, and a map f: {1, ..., m} → {1, ..., m} encoding the action of x(n). We enumerate all such f and check whether this yields an action.
Finally, to compute faithful Wilke algebras, we start with semigroup actions and enumerate all possible values of the power on idempotent elements.
* Output format
The program outputs two text files, actions.data, provided here for n=6,m=4, and wilke.data, provided here for n=5,m=4 and n=6,m=3.
actions.data has the following format: There are blocks separated by "G" denoting actions of a single semigroup. They start with the multiplication table of the semigroup, with row i containing all values of x(i)*x(j). Then lines denoted "A"k separate actions on sets of size k. Each such action is given by its table, with each line denoting the action of a semigroup element.
wilke.data consists of blocks for each Wilke algebra. The first part after "G" contains the multiplication table of the underlying semigroup, the second part after "A" contains the action, and the third part after "W" the power operation.
